### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by strukturart** [strukturart/feedolin#10]
- [x] settings sleeptimer as selectbox
- [x] Activitypub ?
- [x] background sync
- [x] settings toaster
- [x] youtube player bug when closing
- [x]  KaiOS3 export settings bug
- [x] closing app -> background when playing audio
