### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by strukturart** [strukturart/feedolin#14]
- [x] make startup/loading faster
- [x] open article jump2top
- [x] come back to article list jumpt to read article
- [x] show loading progress
- [x] parse cdata
- [x] use cache api!!
